### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by maandree** [dariost/XRainbow#1]
It would be nice if xrainbow supported multimonitor setups. You will have to switch from xvidmode to xrandr for that; or you could use [libgamma](https://github.com/maandree/libgamma/), and then it is not limited to X11 anymore.

**Comment by dariost** [comment]
XRainbow was made to have as few dependencies as possible, so I won't use libgamma (which seems awesome for the things XRainbow does).
However I created another version of XRainbow called [GRainbow](https://github.com/dariost/GRainbow) which use libgamma. I don't have a multi-monitor setup, so I can't test it, but it should work.
Also, since libgamma as far as I understand should work also on Windows, if you could be kind enough to create mingw-w64-libgamma packages for the AUR I'll try to make GRainbow work also on Windows.

P.S. Thanks for all the good programs you've make, like pony.computer

**Comment by maandree** [comment]
I don't have windows nor any experience with mingw, so I will not create such package myself.
